import {
  LayoutDashboard,
  ClipboardList,
  MessageSquare,
  Briefcase,
  FileText as ReportIcon,
  BarChart3,
  Receipt,
  UserCircle,
  Mail,
  FolderOpen,
  Clock,
  Users,
  MessagesSquare,
  BookOpen,
  FileText,
} from 'lucide-react'

export const roleNav: Record<
  string,
  { name: string; href: string; icon: any }[]
> = {
  ceo: [
    { name: 'Dashboard', href: '/ceo/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/ceo/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/ceo/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/ceo/tasks', icon: Briefcase },
    { name: 'Sales Reports', href: '/ceo/sales-reports', icon: ReportIcon },
    { name: 'Reports', href: '/ceo/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/ceo/expenses', icon: Receipt },
    { name: 'Customers', href: '/ceo/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/ceo/clientconnect', icon: Mail },
    { name: 'Files', href: '/ceo/files', icon: FolderOpen },
    { name: 'Attendance', href: '/ceo/attendance', icon: Clock },
    { name: 'Users', href: '/ceo/staff', icon: Users },
    { name: 'Forum', href: '/ceo/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/ceo/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/ceo/company-handbook', icon: FileText },
  ],
  manager: [
    { name: 'Dashboard', href: '/manager/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/manager/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/manager/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/manager/tasks', icon: Briefcase },
    { name: 'Sales Reports', href: '/manager/sales-reports', icon: ReportIcon },
    { name: 'Reports', href: '/manager/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/manager/expenses', icon: Receipt },
    { name: 'Customers', href: '/manager/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/manager/clientconnect', icon: Mail },
    { name: 'Files', href: '/manager/files', icon: FolderOpen },
    { name: 'Attendance', href: '/manager/attendance', icon: Clock },
    { name: 'Users', href: '/manager/staff', icon: Users },
    { name: 'Forum', href: '/manager/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/manager/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/manager/company-handbook', icon: FileText },
  ],
  executive_assistant: [
    { name: 'Dashboard', href: '/executive_assistant/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/executive_assistant/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/executive_assistant/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/executive_assistant/tasks', icon: Briefcase },
    { name: 'Sales Reports', href: '/executive_assistant/sales-reports', icon: ReportIcon },
    { name: 'Reports', href: '/executive_assistant/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/executive_assistant/expenses', icon: Receipt },
    { name: 'Customers', href: '/executive_assistant/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/executive_assistant/clientconnect', icon: Mail },
    { name: 'Files', href: '/executive_assistant/files', icon: FolderOpen },
    { name: 'Attendance', href: '/executive_assistant/attendance', icon: Clock },
    { name: 'Users', href: '/executive_assistant/staff', icon: Users },
    { name: 'Forum', href: '/executive_assistant/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/executive_assistant/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/executive_assistant/company-handbook', icon: FileText },
  ],
  staff: [
    { name: 'Dashboard', href: '/staff/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/staff/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/staff/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/staff/tasks', icon: Briefcase },
    { name: 'Reports', href: '/staff/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/staff/expenses', icon: Receipt },
    { name: 'Customers', href: '/staff/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/staff/clientconnect', icon: Mail },
    { name: 'Files', href: '/staff/files', icon: FolderOpen },
    { name: 'Attendance', href: '/staff/attendance', icon: Clock },
    { name: 'Users', href: '/staff/staff', icon: Users },
    { name: 'Forum', href: '/staff/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/staff/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/staff/company-handbook', icon: FileText },
  ],
  intern: [
    { name: 'Dashboard', href: '/intern/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/intern/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/intern/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/intern/tasks', icon: Briefcase },
    { name: 'Sales Reports', href: '/intern/sales-reports', icon: ReportIcon },
    { name: 'Reports', href: '/intern/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/intern/expenses', icon: Receipt },
    { name: 'Customers', href: '/intern/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/intern/clientconnect', icon: Mail },
    { name: 'Files', href: '/intern/files', icon: FolderOpen },
    { name: 'Attendance', href: '/intern/attendance', icon: Clock },
    { name: 'Users', href: '/intern/staff', icon: Users },
    { name: 'Forum', href: '/intern/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/intern/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/intern/company-handbook', icon: FileText },
  ],
  sales_representative: [
    { name: 'Dashboard', href: '/sales_representative/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/sales_representative/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/sales_representative/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/sales_representative/tasks', icon: Briefcase },
    { name: 'Daily Reports', href: '/sales_representative/daily-reports', icon: ReportIcon },
    { name: 'Reports', href: '/sales_representative/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/sales_representative/expenses', icon: Receipt },
    { name: 'Customers', href: '/sales_representative/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/sales_representative/clientconnect', icon: Mail },
    { name: 'Files', href: '/sales_representative/files', icon: FolderOpen },
    { name: 'Attendance', href: '/sales_representative/attendance', icon: Clock },
    { name: 'Users', href: '/sales_representative/staff', icon: Users },
    { name: 'Forum', href: '/sales_representative/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/sales_representative/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/sales_representative/company-handbook', icon: FileText },
  ],
  board: [
    { name: 'Dashboard', href: '/board/dashboard', icon: LayoutDashboard },
    { name: 'Orders', href: '/board/orders', icon: ClipboardList },
    { name: 'Enquiries', href: '/board/enquiries', icon: MessageSquare },
    { name: 'Tasks', href: '/board/tasks', icon: Briefcase },
    { name: 'Reports', href: '/board/reports', icon: BarChart3 },
    { name: 'Expenses', href: '/board/expenses', icon: Receipt },
    { name: 'Customers', href: '/board/customers', icon: UserCircle },
    { name: 'Client Connect', href: '/board/clientconnect', icon: Mail },
    { name: 'Files', href: '/board/files', icon: FolderOpen },
    { name: 'Attendance', href: '/board/attendance', icon: Clock },
    { name: 'Users', href: '/board/staff', icon: Users },
    { name: 'Forum', href: '/board/forum', icon: MessagesSquare },
    { name: 'App Handbook', href: '/board/handbook', icon: BookOpen },
    { name: 'UPP Handbook', href: '/board/company-handbook', icon: FileText },
  ],
}
